[package]
name = "iterator-vec-demo"
version = "0.1.0"
authors = ["unmyr <56982541+unmyr@users.noreply.github.com>"]
edition = "2018"

[[bin]]
name = "for-demo"
path = "src/main.rs"

[[test]]
name = "all"
path = "src/test.rs"

[dependencies]
