fmt:
	(cd cacher && cargo fmt)
	(cd counter && cargo fmt)
	(cd exercise_workout && cargo fmt)
	(cd minigrep && cargo fmt)

clean:
	(cd cacher && cargo clean)
	(cd counter && cargo clean)
	(cd exercise_workout && cargo clean)
	(cd minigrep && cargo clean)
