== Recoverable Errors with Result

=== Set up a new project
. Set up a new project, and go to the projects directory.
+
[source,console]
----
$ cargo new --bin tutorials/chap13
     Created binary (application) `tutorials/chap13` package
$ cd tutorials/chap13/
----

=== Closures: Anonymous Functions that Can Capture Their Environment

* https://doc.rust-lang.org/book/ch13-01-closures.html[Closures: Anonymous Functions that Can Capture Their Environment - The Rust Programming Language^]

==== Creating an Abstraction of Behavior with Closures

===== Listing 13-1: A function to stand in for a hypothetical calculation that takes about 2 seconds to run

[source,rust]
.src/main.rs
----
use std::thread;
use std::time::Duration;

fn simulated_expensive_calculation(intensity: u32) -> u32 {
    println!("calculating slowly...");
    thread::sleep(Duration::from_secs(2));
    intensity
}

fn main() {}
----

===== Listing 13-2: A main function with hardcoded values to simulate user input and random number generation

[source,rust]
.src/main.rs
----
use std::thread;
use std::time::Duration;

fn simulated_expensive_calculation(intensity: u32) -> u32 {
    println!("calculating slowly...");
    thread::sleep(Duration::from_secs(2));
    intensity
}

fn generate_workout(intensity: u32, random_number: u32) {}

fn main() {
    let simulated_user_specified_value = 10;
    let simulated_random_number = 7;

    generate_workout(simulated_user_specified_value, simulated_random_number);
}
----

===== Listing 13-3: The business logic that prints the workout plans based on the inputs and calls to the simulated_expensive_calculation function

[source,rust]
.src/main.rs
----
use std::thread;
use std::time::Duration;

fn simulated_expensive_calculation(intensity: u32) -> u32 {
    println!("calculating slowly...");
    thread::sleep(Duration::from_secs(2));
    intensity
}

fn generate_workout(intensity: u32, random_number: u32) {
    if intensity < 25 {
        println!(
            "Today, do {} pushups!",
            simulated_expensive_calculation(intensity)
        );
        println!(
            "Next, do {} situps!",
            simulated_expensive_calculation(intensity)
        );
    } else {
        if random_number == 3 {
            println!("Take a break today! Remember to stay hydrated!");
        } else {
            println!(
                "Today, run for {} minutes!",
                simulated_expensive_calculation(intensity)
            );
        }
    }
}

fn main() {
    let simulated_user_specified_value = 10;
    let simulated_random_number = 7;

    generate_workout(simulated_user_specified_value, simulated_random_number);
}
----

=== Refactoring Using Functions

==== Creating an Abstraction of Behavior with Closures

===== Listing 13-4: Extracting the calls to simulated_expensive_calculation to one place and storing the result in the expensive_result variable

[source,diff]
.git diff tutorials/chap13/src/main.rs
----
@@ -8,23 +8,16 @@ fn simulated_expensive_calculation(intensity: u32) -> u32 {
 }
 
 fn generate_workout(intensity: u32, random_number: u32) {
+    let expensive_result = simulated_expensive_calculation(intensity);
+
     if intensity < 25 {
-        println!(
-            "Today, do {} pushups!",
-            simulated_expensive_calculation(intensity)
-        );
-        println!(
-            "Next, do {} situps!",
-            simulated_expensive_calculation(intensity)
-        );
+        println!("Today, do {} pushups!", expensive_result);
+        println!("Next, do {} situps!", expensive_result);
     } else {
         if random_number == 3 {
             println!("Take a break today! Remember to stay hydrated!");
         } else {
-            println!(
-                "Today, run for {} minutes!",
-                simulated_expensive_calculation(intensity)
-            );
+            println!("Today, run for {} minutes!", expensive_result);
         }
     }
 }
----