[workspace]
members = [
    "digits_sum_has_nth_roots",
    "factorial",
    "itertools-examples",
    "nalgebra-example-mutmal",
    "ndarray-example-mutmal",
    "necklace-permutations",
    "permutation",
    "tsp-basic",
]
