[workspace]
members = [
    "collatz",
    "digits_sum_has_nth_roots",
    "factorial",
    "group-o2-c2",
    "itertools-examples",
    "monte-carlo",
    "nalgebra-example-mutmal",
    "ndarray-example-mutmal",
    "necklace-permutations",
    "permutation",
    "primes",
    "tsp-basic",
]
