ifndef::leveloffset[]
:toc: left
:toclevels: 3
:icons: font
endif::[]

=== Set up a new project
. Set up a new project, and go to the projects directory.
+
[source,console]
----
$ cargo new --lib singly-linked-list-using-box
     Created library `singly-linked-list-using-box` package
$ cd singly-linked-list-using-box/
----

=== References

* https://stackoverflow.com/questions/55062035/what-would-be-a-better-way-to-implement-pop-in-my-single-linked-list-in-rust[What would be a better way to implement .pop() in my single linked list in Rust? - Stack Overflow^] +
  rust singly linked list peek - Google 検索
* https://stackoverflow.com/questions/41653148/singly-linked-list-in-rust[Singly-Linked List in Rust - Stack Overflow^] +
  rust box LinkedList - Google Search
* https://gist.github.com/hardvain/32fca033bb61a5e3bf8bbeeb32fbbd5e[Singly Linked List in Rust - gists · GitHub^] +
  rust pub singly linked list iter - Google 検索
* Raw pointer
** https://11takanori.medium.com/singly-linked-list-in-rust-70a7c2cfa162[Singly-Linked List in Rust. 本記事は“Open Data Structures”… | by Takanori Ishibashi | Medium^] +
   rust singly linked list box - Google 検索
** https://github.com/rust-lang/rust/blob/master/library/alloc/src/collections/linked_list.rs[rust/linked_list.rs at master · rust-lang/rust^] +
   rust std LinkedList github - Google 検索
** https://rust-unofficial.github.io/too-many-lists/[Learning Rust With Entirely Too Many Linked Lists - GitHub ...^] +
   rust std LinkedList github - Google 検索

=== Code

* <<docs/v1.adoc#,v1>> +
  v1 of the push_back function uses a recursive algorithm.
* <<docs/v1.adoc#,v2>> +
  The push_back function v2 improves the recursive algorithm to a iterative algorithm.

==== Prototype

[source,rust]
----
struct ListNode<T> {
    value: T,
    next: Option<Box<ListNode<T>>>,
}

#[derive(Default)]
pub struct SinglyLinkedList<T> {
    head: Option<Box<ListNode<T>>>,
}

pub struct SinglyLinkedListIterator<'a, T:'a> {
    next: Option<&'a ListNode<T>>
}

impl<T> ListNode<T> {
    pub fn new(v: T) -> ListNode<T> {
        ListNode { value: v, next: None }
    }
}

impl<T> SinglyLinkedList<T> {
    /// # Examples
    ///
    /// ```
    /// use list::SinglyLinkedList;
    /// let mut list: SinglyLinkedList<u8> = Default::default();
    /// list.push_back(1);
    /// list.push_back(2);
    /// ```
    pub fn push_back(&mut self, v: T) {}

    /// # Examples
    ///
    /// ```
    /// use list::SinglyLinkedList;
    /// let mut list: SinglyLinkedList<u8> = Default::default();
    /// list.push_back(1);
    /// list.push_back(2);
    /// assert_eq!(list.pop_back(), Some(2));
    /// assert_eq!(list.pop_back(), Some(1));
    /// assert_eq!(list.pop_back(), None);
    /// ```
    pub fn pop_back(&mut self) -> Option<T> { None }

    /// # Examples
    ///
    /// ```
    /// use list::SinglyLinkedList;
    /// let mut list: SinglyLinkedList<u8> = Default::default();
    /// list.push_back(1);
    /// list.push_back(2);
    /// assert_eq!(list.pop_front(), Some(1));
    /// assert_eq!(list.pop_front(), Some(2));
    /// assert_eq!(list.pop_front(), None);
    /// ```
    pub fn pop_front(&mut self) -> Option<T> { None }

    /// # Examples
    ///
    /// ```
    /// use singly_linked_list_using_box::v2::SinglyLinkedList;
    /// let mut list: SinglyLinkedList<u8> = Default::default();
    /// list.push_back(1);
    /// list.push_back(2);
    /// let mut iter = list.iter();
    /// assert_eq!(iter.next(), Some(&1));
    /// assert_eq!(iter.next(), Some(&2));
    /// assert_eq!(iter.next(), None);
    /// ```
    pub fn iter(&self) -> SinglyLinkedListIterator<'_,T> {
        return SinglyLinkedListIterator {
            next: self.head.as_deref()
        }
    }
}
----