[package]
name = "tsp-basic"
version = "0.1.0"
edition = "2021"

[lib]
name = "tsplib"
path = "src/lib.rs"

[dependencies]
regex = "1"
rand = "0.8"
necklace-permutations = { path = "../necklace-permutations" }
pathfinder_simd = { version = "0.5", features = ["pf-no-simd"] }
plotters = "0.3"
