fmt:
	(cd ch15-06-circular-references && cargo fmt)
	(cd cons_list && cargo fmt)
	(cd deref_example && cargo fmt)

clean:
	(cd ch15-06-circular-references && cargo clean)
	(cd cons_list && cargo clean)
	(cd deref_example && cargo clean)
