fmt:
	(cd chapter10 && cargo fmt)
	(cd largest && cargo fmt)
	(cd point && cargo fmt)
	(cd summary-trait && cargo fmt)

clean:
	(cd chapter10 && cargo clean)
	(cd largest && cargo clean)
	(cd point && cargo clean)
	(cd summary-trait && cargo clean)
