[workspace]
members = [
    "capture-by-move",
    "capture-values",
    "closure-in-struct",
    "get-closures-imm",
    "get-closures-mut",
    "immutable-borrow",
    "joint-capturing",
    "mutable-borrow",
    "return-a-reference",
]
