clean:
	(cd capture-by-move && cargo clean)
	(cd capture-values && cargo clean)
	(cd get-closures-imm && cargo clean)
	(cd immutable-borrow && cargo clean)
	(cd joint-capturing && cargo clean)
	(cd mutable-borrow && cargo clean)
