== Recoverable Errors with Result

* https://doc.rust-lang.org/book/ch10-00-generics.html[Generic Types, Traits, and Lifetimes - The Rust Programming Language^]
* https://doc.rust-lang.org/book/ch10-02-traits.html[Traits: Defining Shared Behavior - The Rust Programming Language^] +
  rust struct mut field - Google Search

=== Set up a new project
. Set up a new project, and go to the projects directory.
+
[source,console]
----
$ cargo new --lib largest
     Created library `largest` package
$ cd largest/
----

=== Run binary

[source,console]
----
$ cargo run --bin largest_i32_char
----

[source,console]
----
$ cargo run --bin largest_gen
----


=== Run tests

[source,console]
.Results
----
$ cargo test
...
----


=== Removing Duplication by Extracting a Function

==== Code to find the largest number in a list of numbers
[source,rust]
.src/largest_i32.rs
----
fn main() {
    let number_list = vec![34, 50, 25, 100, 65];

    let mut largest = number_list[0];

    for number in number_list {
        if number > largest {
            largest = number;
        }
    }

    println!("The largest number is {}", largest);
}
----

[source,console]
----
chap10$ cargo run --bin largest_i32
   Compiling chap10 v0.1.0 (<path-to-project>/chap10)
    Finished dev [unoptimized + debuginfo] target(s) in 2.15s
     Running `target/debug/largest_i32`
The largest number is 100
----

==== Code to find the largest number in two lists of numbers

[source,rust]
.src/largest_i32.rs
----
fn main() {
    let number_list = vec![34, 50, 25, 100, 65];

    let mut largest = number_list[0];

    for number in number_list {
        if number > largest {
            largest = number;
        }
    }

    println!("The largest number is {}", largest);

    let number_list = vec![102, 34, 6000, 89, 54, 2, 43, 8];

    let mut largest = number_list[0];

    for number in number_list {
        if number > largest {
            largest = number;
        }
    }

    println!("The largest number is {}", largest);
}
----

[source,console]
----
chap10$ cargo run --bin largest_i32
   Compiling chap10 v0.1.0 (<path-to-project>/chap10)
    Finished dev [unoptimized + debuginfo] target(s) in 1.79s
     Running `target/debug/largest_i32`
The largest number is 100
The largest number is 6000
----

==== Abstracted code to find the largest number in two lists
[source,rust]
----
fn largest(list: &[i32]) -> &i32 {
    let mut largest = &list[0];

    for item in list {
        if item > largest {
            largest = item;
        }
    }

    largest
}

fn main() {
    let number_list = vec![34, 50, 25, 100, 65];

    let result = largest(&number_list);
    println!("The largest number is {}", result);

    let number_list = vec![102, 34, 6000, 89, 54, 2, 43, 8];

    let result = largest(&number_list);
    println!("The largest number is {}", result);
}
----

[source,console]
----
chap10$ cargo run --bin largest_i32
   Compiling chap10 v0.1.0 (<path-to-project>/chap10)
    Finished dev [unoptimized + debuginfo] target(s) in 2.27s
     Running `target/debug/largest_i32`
The largest number is 100
The largest number is 6000
----

== Generic Data Types
* https://doc.rust-lang.org/book/ch10-01-syntax.html[Generic Data Types - The Rust Programming Language^]

=== In Function Definitions

==== Two functions that differ only in their names and the types in their signatures

[source,rust]
----
fn largest_i32(list: &[i32]) -> &i32 {
    let mut largest = &list[0];

    for item in list {
        if item > largest {
            largest = item;
        }
    }

    largest
}

fn largest_char(list: &[char]) -> &char {
    let mut largest = &list[0];

    for item in list {
        if item > largest {
            largest = item;
        }
    }

    largest
}

fn main() {
    let number_list = vec![34, 50, 25, 100, 65];

    let result = largest_i32(&number_list);
    println!("The largest number is {}", result);

    let char_list = vec!['y', 'm', 'a', 'q'];

    let result = largest_char(&char_list);
    println!("The largest char is {}", result);
}
----

[source,console]
----
chap10$ cargo run --bin largest_generic
   Compiling chap10 v0.1.0 (<path-to-project>/chap10)
    Finished dev [unoptimized + debuginfo] target(s) in 1.84s
     Running `target/debug/largest_generic`
The largest number is 100
The largest char is y
----


==== A definition of the largest function that uses generic type parameters but doesn’t compile yet

[source,rust]
----
fn largest<T: PartialOrd>(list: &[T]) -> &T {
    let mut largest = &list[0];

    for item in list {
        if item > largest {
            largest = item;
        }
    }

    largest
}

fn main() {
    let number_list = vec![34, 50, 25, 100, 65];

    let result = largest(&number_list);
    println!("The largest number is {}", result);

    let char_list = vec!['y', 'm', 'a', 'q'];

    let result = largest(&char_list);
    println!("The largest char is {}", result);
}
----

[source,console]
----
chap10$ cargo run --bin largest_generic
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/largest_generic`
The largest number is 100
The largest char is y
----
